/**
 *
 */
package org.openmrs.module.mohbilling.model;

/**
 * @author EMR@RBC
 *
 */
public enum Category {

	CHIRURGIE ("CHIRURGIE"),CONSOMMABLES("CONSOMMABLES"),
	CONSULTATION ("CONSULTATION"),
	DERMATOLOGIE ("DERMATOLOGIE"),
	ECHOGRAPHIE ("ECHOGRAPHIE"),
	RADIOGRAPHIE("RADIOGRAPHIE"),
	FORMALITES_ADMINISTRATIVES ("FORMALITES ADMINISTRATIVES"),
	HOSPITALISATION ("HOSPITALISATION"),
	KINESITHERAPIE ("KINESITHERAPIE"),LABORATOIRE ("LABORATOIRE"),
	MATERNITE ("MATERNITE"),MEDECINE_INTERNE ("MEDECINE INTERNE"),
	MEDICAMENTS ("MEDICAMENTS"),OPHTALMOLOGIE ("OPHTALMOLOGIE"),
	ORL ("ORL"),OXYGENOTHERAPIE ("OXYGENOTHERAPIE"),PEDIATRIE ("PEDIATRIE"),
	RADIOLOGIE ("RADIOLOGIE"),SOINS_INFIRMIERS ("SOINS INFIRMIERS"),
	SOINS_INTENSIFS ("SOINS INTENSIFS"),STOMATOLOGIE ("STOMATOLOGIE"),
	NEUROLOGIE("NEUROLOGIE"),AUTRES("AUTRES"),AMBULANCE("AMBULANCE"),
	GYNECO_OBSTETRIQUE ("GYNECO - OBSTETRIQUE"),
	POLYCLINIQUE("POLYCLINIQUE"),
	APPAREILLAGE_ORTHOPEDIQUE("APPAREILLAGE ORTHOPEDIQUE"),
	MORGUE("MORGUE"),
	MAGNETIC_RESONANCE_IMAGING("MAGNETIC RESONANCE IMAGING"),
	DCP_CONSULTATION("DCP CONSULTATION"),
	DCP_SURGERY("DCP SURGERY"),
	DCP_INTERNAL_MEDECINE("DCP INTERNAL MEDECINE"),
	DCP_PEDIATRICS("DCP PEDIATRICS"),
	DCP_DERMATOLOGY("DCP DERMATOLOGY"),
	DCP_OBSTETRICS_GYNECOLOGY("DCP OBSTETRICS-GYNECOLOGY"),
	DCP_OPHTHALMOLOGY("DCP OPHTHALMOLOGY"),
	DCP_STOMATOLOGY("DCP STOMATOLOGY"),
	DCP_OTORHINOLARYNGOLOGIE("DCP OTORHINOLARYNGOLOGIE (ENT/ORL)"),
	DCP_ANESTHESIE("DCP ANESTHESIE");
	private final String description;

	private Category(String name) {
		this.description = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}
}