/**
 *
 */
package org.openmrs.module.mohbilling.model;

/**
 * @author EMR@RBC
 *
 */
public enum Category {

	CHIRURGIE ("CHIRURGIE"),
	CONSOMMABLES("CONSOMMABLES"),
	CONSULTATION ("CONSULTATION"),
	DERMATOLOGIE ("DERMATOLOGIE"),
	ECHOGRAPHIE ("ECHOGRAPHIE"),
	RADIOGRAPHIE("RADIOGRAPHIE"),
	FORMALITES_ADMINISTRATIVES ("FORMALITES ADMINISTRATIVES"),
	HOSPITALISATION ("HOSPITALISATION"),
	KINESITHERAPIE ("KINESITHERAPIE"),
	LABORATOIRE ("LABORATOIRE"),
	MATERNITE ("MATERNITE"),
	MEDECINE_INTERNE ("MEDECINE INTERNE"),
	MEDICAMENTS ("MEDICAMENTS"),
	OPHTALMOLOGIE ("OPHTALMOLOGIE"),
	ORL ("ORL"),
	OXYGENOTHERAPIE ("OXYGENOTHERAPIE"),
	PEDIATRIE ("PEDIATRIE"),
	RADIOLOGIE ("RADIOLOGIE"),
	SOINS_INFIRMIERS ("SOINS INFIRMIERS"),
	SOINS_INTENSIFS ("SOINS INTENSIFS"),
	STOMATOLOGIE ("STOMATOLOGIE"),
	NEUROLOGIE("NEUROLOGIE"),
	AUTRES("AUTRES"),
	AMBULANCE("AMBULANCE"),
	GYNECO_OBSTETRIQUE ("GYNECO - OBSTETRIQUE"),
	POLYCLINIQUE("POLYCLINIQUE"),
	APPAREILLAGE_ORTHOPEDIQUE("APPAREILLAGE ORTHOPEDIQUE"),
	MORGUE("MORGUE"),
	MAGNETIC_RESONANCE_IMAGING("MAGNETIC RESONANCE IMAGING"),
	OCCUPATIONALTHERAPY("OCCUPATIONALTHERAPY"),
	ANAESTHESIA("ANAESTHESIA"), CARDIOLOGY("CARDIOLOGY"), CT_SURGERY("CT SURGERY"),
	DENTISTRY("DENTISTRY"), DERMATOLOGY("DERMATOLOGY"), ENT("ENT"),
	EMERGENCY_CRITICAL_CARE("EMERGENCY CRITICAL CARE"), GASTROENTEROLOGY("GASTROENTEROLOGY"),
	GENERAL_SURGERY("GENERAL SURGERY"), HOSPITALIZATION("HOSPITALIZATION"),
	IMAGING_MRI("IMAGING MRI"), IMAGING_X_RAY("IMAGING X RAY"), IMAGING_CT_SCAN("IMAGING CT SCAN"),
	IMAGING_INTERVENTIONAL("IMAGING INTERVENTIONAL"), IMAGING_ULTRASOUND("IMAGING ULTRASOUND"),
	OB_GYN("OB GYN"), MAXILLOFACIAL_SURGERY("MAXILLOFACIAL SURGERY"),
	MEDICAL_PROCEDURES("MEDICAL PROCEDURES"), MENTAL_HEALTH("MENTAL HEALTH"),
	MINOR_SURGERY("MINOR SURGERY"), NEPHROLOGY("NEPHROLOGY"),
	NEUROSURGERY("NEUROSURGERY"), NEUROLOGY("NEUROLOGY"),
	NURSING("NURSING"), OCCUPATIONAL_THERAPY("OCCUPATIONAL THERAPY"),
	ONCOLOGY("ONCOLOGY"), OPHTHALMOLOGY("OPHTHALMOLOGY"),ORTHOPEDICS("ORTHOPEDICS"),
	PEDIATRIC_SURGERY("PEDIATRIC SURGERY"), PHYSIOTHERAPY("PHYSIOTHERAPY"),
	PLASTIC_SURGERY("PLASTIC SURGERY"), PULMONOLOGY("PULMONOLOGY"),
	UROLOGY("UROLOGY"), VASCULAR_SURGERY("VASCULAR SURGERY"),
	LABORATORY("LABORATORY"), ADMINISTRATION("ADMINISTRATION"),
	DCP_CONSULTATION("DCP CONSULTATION"),
	DCP_SURGERY("DCP SURGERY"),
	DCP_INTERNAL_MEDECINE("DCP INTERNAL MEDECINE"),
	DCP_PEDIATRICS("DCP PEDIATRICS"),
	DCP_DERMATOLOGY("DCP DERMATOLOGY"),
	DCP_OBSTETRICS_GYNECOLOGY("DCP OBSTETRICS-GYNECOLOGY"),
	DCP_OPHTHALMOLOGY("DCP OPHTHALMOLOGY"),
	DCP_STOMATOLOGY("DCP STOMATOLOGY"),
	DCP_OTORHINOLARYNGOLOGIE("DCP OTORHINOLARYNGOLOGIE (ENT/ORL)"),
	DCP_ANESTHESIE("DCP ANESTHESIE");
	private final String description;

	private Category(String name) {
		this.description = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}
}