/*
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.mohbilling.integration.irembopay.dto;

import java.util.List;

public class IremboPayInvoiceDto {
    /**
     * A unique transaction identifier generated by the merchant.
     */
    private String transactionId;

    /**
     * Identifier of the Payment Account where the money will be deposited. It also determines the currency of the invoice.
     */
    private String paymentAccountIdentifier;

    /**
     * An optional customer object who will be notified about this invoice.
     */
    private CustomerDto customer;

    /**
     * List of products to include in the invoice. Each product has a unit amount. Find more details on the structure of this array after this table.
     */
    private List<PaymentItemDto> paymentItems;

    /**
     * An optional description of the invoice.
     */
    private String description;

    /**
     * Time at which the payment request will expire, in Internet date and time format. eg.2022-11-27T16:24:51.000+02:00
     */
    private String expiryAt;

    /**
     * Language provided during the creation of the invoice.
     * Possible values: FR, EN, RW.
     */
    private String language;

    public IremboPayInvoiceDto() {
        // no-arg constructor for Jackson
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getPaymentAccountIdentifier() {
        return paymentAccountIdentifier;
    }

    public void setPaymentAccountIdentifier(String paymentAccountIdentifier) {
        this.paymentAccountIdentifier = paymentAccountIdentifier;
    }

    public CustomerDto getCustomer() {
        return customer;
    }

    public void setCustomer(CustomerDto customer) {
        this.customer = customer;
    }

    public List<PaymentItemDto> getPaymentItems() {
        return paymentItems;
    }

    public void setPaymentItems(List<PaymentItemDto> paymentItems) {
        this.paymentItems = paymentItems;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExpiryAt() {
        return expiryAt;
    }

    public void setExpiryAt(String expiryAt) {
        this.expiryAt = expiryAt;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

}
